//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/02 - Characters/Player_Input_Action.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player_Input_Action: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player_Input_Action()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player_Input_Action"",
    ""maps"": [
        {
            ""name"": ""Player1"",
            ""id"": ""4ff67dcc-8ca7-443c-91c8-6adea16e2640"",
            ""actions"": [
                {
                    ""name"": ""RightUpDiagonal"",
                    ""type"": ""Button"",
                    ""id"": ""ee21e9bb-05e5-47aa-8107-bbf20adb9bb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""a77808a8-14be-4288-ab4c-76cd40a68e3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightDownDiagonal"",
                    ""type"": ""Button"",
                    ""id"": ""64a1caac-daac-4eca-8745-01779615e196"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""6f4c0bac-7b1b-48f3-86e7-3f098ac37846"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftDownDiagonal"",
                    ""type"": ""Button"",
                    ""id"": ""315ed34a-a916-4a50-8665-15fdab716a62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""c92db9d9-f721-4113-89d1-605d98385e6c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftUpDiagonal"",
                    ""type"": ""Button"",
                    ""id"": ""667af4ac-0345-4b90-a904-34db7dedc1ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""67c8e364-05cb-4ae4-8b85-ee5cec666db9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DashRight"",
                    ""type"": ""Button"",
                    ""id"": ""0262ac13-9e20-4284-bc09-e3542cf6c46d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DashLeft"",
                    ""type"": ""Button"",
                    ""id"": ""f0f5ba0e-9d10-4c51-899d-2badf4be1e47"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LP"",
                    ""type"": ""Button"",
                    ""id"": ""fa8f7df6-e6f0-4c7b-9009-a1095aae9064"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MP"",
                    ""type"": ""Button"",
                    ""id"": ""278a7ae1-b0b2-4873-90b2-4d118aa147d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HP"",
                    ""type"": ""Button"",
                    ""id"": ""88bc7cea-70d4-4945-8b9a-c32328a05fb9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LK"",
                    ""type"": ""Button"",
                    ""id"": ""ed160af1-4d5f-4705-8ae2-2c08e927e671"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MK"",
                    ""type"": ""Button"",
                    ""id"": ""353fce9a-576d-4770-aa34-84aa97e91118"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HK"",
                    ""type"": ""Button"",
                    ""id"": ""5c4d07de-3713-4e51-b659-19f802e75800"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a3246c7e-6b8f-4319-a94b-d46a3ae67a05"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""943880be-0ab4-4557-af2a-d7e949a82c42"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83f7ccbd-7cb7-4a36-b101-6532711893dc"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76daa8b7-495e-4aa2-a634-be1a52f4cdbd"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cd0b5a4-d6ec-4369-9430-f6621162a7f5"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""459e3f28-948e-4435-91e9-2c81ebaaac70"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15a71e0b-09d8-4531-9883-782314349548"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89ccf1e9-de2c-464b-ab5d-495c9636c211"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a582702-a949-446b-8413-22924726ddfe"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af2f13cc-3952-48c0-90e2-dcfd5a2258b3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""D & S"",
                    ""id"": ""a6faa67f-e4df-4727-9dfe-ecad09694f20"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDownDiagonal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8c600620-f1eb-4de2-ab70-df7a869ba6f9"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDownDiagonal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d6f06a75-94ea-4454-bd47-ce6e5ff56900"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDownDiagonal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2f383b6c-0f40-426c-be80-80827e265b48"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""A & S"",
                    ""id"": ""a3a318e6-cff2-4928-bf98-46cbdf6e2bae"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDownDiagonal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""3fe00e7c-f177-4a79-894d-de71e6531daf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDownDiagonal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e8984b02-7c3b-495f-b58c-072c3ccade06"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDownDiagonal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""A & W"",
                    ""id"": ""f6747692-f8a0-4360-9600-9d27ba451d56"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftUpDiagonal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""afc3a173-9b86-447f-9c08-396daaa29708"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftUpDiagonal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5196122e-440e-4fec-8dfb-459f0e17f211"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftUpDiagonal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""D & W"",
                    ""id"": ""f1a60459-3998-4129-a171-809bd5d4cc7a"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightUpDiagonal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""19062d30-35e4-43dc-9757-126c21ffb96c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightUpDiagonal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""2dce5a39-a06c-4732-95cd-3d9c56471394"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightUpDiagonal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1aebcb55-21f7-4666-9f00-6f6bf33dc662"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player1
        m_Player1 = asset.FindActionMap("Player1", throwIfNotFound: true);
        m_Player1_RightUpDiagonal = m_Player1.FindAction("RightUpDiagonal", throwIfNotFound: true);
        m_Player1_Right = m_Player1.FindAction("Right", throwIfNotFound: true);
        m_Player1_RightDownDiagonal = m_Player1.FindAction("RightDownDiagonal", throwIfNotFound: true);
        m_Player1_Down = m_Player1.FindAction("Down", throwIfNotFound: true);
        m_Player1_LeftDownDiagonal = m_Player1.FindAction("LeftDownDiagonal", throwIfNotFound: true);
        m_Player1_Left = m_Player1.FindAction("Left", throwIfNotFound: true);
        m_Player1_LeftUpDiagonal = m_Player1.FindAction("LeftUpDiagonal", throwIfNotFound: true);
        m_Player1_Up = m_Player1.FindAction("Up", throwIfNotFound: true);
        m_Player1_DashRight = m_Player1.FindAction("DashRight", throwIfNotFound: true);
        m_Player1_DashLeft = m_Player1.FindAction("DashLeft", throwIfNotFound: true);
        m_Player1_LP = m_Player1.FindAction("LP", throwIfNotFound: true);
        m_Player1_MP = m_Player1.FindAction("MP", throwIfNotFound: true);
        m_Player1_HP = m_Player1.FindAction("HP", throwIfNotFound: true);
        m_Player1_LK = m_Player1.FindAction("LK", throwIfNotFound: true);
        m_Player1_MK = m_Player1.FindAction("MK", throwIfNotFound: true);
        m_Player1_HK = m_Player1.FindAction("HK", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player1
    private readonly InputActionMap m_Player1;
    private List<IPlayer1Actions> m_Player1ActionsCallbackInterfaces = new List<IPlayer1Actions>();
    private readonly InputAction m_Player1_RightUpDiagonal;
    private readonly InputAction m_Player1_Right;
    private readonly InputAction m_Player1_RightDownDiagonal;
    private readonly InputAction m_Player1_Down;
    private readonly InputAction m_Player1_LeftDownDiagonal;
    private readonly InputAction m_Player1_Left;
    private readonly InputAction m_Player1_LeftUpDiagonal;
    private readonly InputAction m_Player1_Up;
    private readonly InputAction m_Player1_DashRight;
    private readonly InputAction m_Player1_DashLeft;
    private readonly InputAction m_Player1_LP;
    private readonly InputAction m_Player1_MP;
    private readonly InputAction m_Player1_HP;
    private readonly InputAction m_Player1_LK;
    private readonly InputAction m_Player1_MK;
    private readonly InputAction m_Player1_HK;
    public struct Player1Actions
    {
        private @Player_Input_Action m_Wrapper;
        public Player1Actions(@Player_Input_Action wrapper) { m_Wrapper = wrapper; }
        public InputAction @RightUpDiagonal => m_Wrapper.m_Player1_RightUpDiagonal;
        public InputAction @Right => m_Wrapper.m_Player1_Right;
        public InputAction @RightDownDiagonal => m_Wrapper.m_Player1_RightDownDiagonal;
        public InputAction @Down => m_Wrapper.m_Player1_Down;
        public InputAction @LeftDownDiagonal => m_Wrapper.m_Player1_LeftDownDiagonal;
        public InputAction @Left => m_Wrapper.m_Player1_Left;
        public InputAction @LeftUpDiagonal => m_Wrapper.m_Player1_LeftUpDiagonal;
        public InputAction @Up => m_Wrapper.m_Player1_Up;
        public InputAction @DashRight => m_Wrapper.m_Player1_DashRight;
        public InputAction @DashLeft => m_Wrapper.m_Player1_DashLeft;
        public InputAction @LP => m_Wrapper.m_Player1_LP;
        public InputAction @MP => m_Wrapper.m_Player1_MP;
        public InputAction @HP => m_Wrapper.m_Player1_HP;
        public InputAction @LK => m_Wrapper.m_Player1_LK;
        public InputAction @MK => m_Wrapper.m_Player1_MK;
        public InputAction @HK => m_Wrapper.m_Player1_HK;
        public InputActionMap Get() { return m_Wrapper.m_Player1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player1Actions set) { return set.Get(); }
        public void AddCallbacks(IPlayer1Actions instance)
        {
            if (instance == null || m_Wrapper.m_Player1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player1ActionsCallbackInterfaces.Add(instance);
            @RightUpDiagonal.started += instance.OnRightUpDiagonal;
            @RightUpDiagonal.performed += instance.OnRightUpDiagonal;
            @RightUpDiagonal.canceled += instance.OnRightUpDiagonal;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @RightDownDiagonal.started += instance.OnRightDownDiagonal;
            @RightDownDiagonal.performed += instance.OnRightDownDiagonal;
            @RightDownDiagonal.canceled += instance.OnRightDownDiagonal;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @LeftDownDiagonal.started += instance.OnLeftDownDiagonal;
            @LeftDownDiagonal.performed += instance.OnLeftDownDiagonal;
            @LeftDownDiagonal.canceled += instance.OnLeftDownDiagonal;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @LeftUpDiagonal.started += instance.OnLeftUpDiagonal;
            @LeftUpDiagonal.performed += instance.OnLeftUpDiagonal;
            @LeftUpDiagonal.canceled += instance.OnLeftUpDiagonal;
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @DashRight.started += instance.OnDashRight;
            @DashRight.performed += instance.OnDashRight;
            @DashRight.canceled += instance.OnDashRight;
            @DashLeft.started += instance.OnDashLeft;
            @DashLeft.performed += instance.OnDashLeft;
            @DashLeft.canceled += instance.OnDashLeft;
            @LP.started += instance.OnLP;
            @LP.performed += instance.OnLP;
            @LP.canceled += instance.OnLP;
            @MP.started += instance.OnMP;
            @MP.performed += instance.OnMP;
            @MP.canceled += instance.OnMP;
            @HP.started += instance.OnHP;
            @HP.performed += instance.OnHP;
            @HP.canceled += instance.OnHP;
            @LK.started += instance.OnLK;
            @LK.performed += instance.OnLK;
            @LK.canceled += instance.OnLK;
            @MK.started += instance.OnMK;
            @MK.performed += instance.OnMK;
            @MK.canceled += instance.OnMK;
            @HK.started += instance.OnHK;
            @HK.performed += instance.OnHK;
            @HK.canceled += instance.OnHK;
        }

        private void UnregisterCallbacks(IPlayer1Actions instance)
        {
            @RightUpDiagonal.started -= instance.OnRightUpDiagonal;
            @RightUpDiagonal.performed -= instance.OnRightUpDiagonal;
            @RightUpDiagonal.canceled -= instance.OnRightUpDiagonal;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @RightDownDiagonal.started -= instance.OnRightDownDiagonal;
            @RightDownDiagonal.performed -= instance.OnRightDownDiagonal;
            @RightDownDiagonal.canceled -= instance.OnRightDownDiagonal;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @LeftDownDiagonal.started -= instance.OnLeftDownDiagonal;
            @LeftDownDiagonal.performed -= instance.OnLeftDownDiagonal;
            @LeftDownDiagonal.canceled -= instance.OnLeftDownDiagonal;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @LeftUpDiagonal.started -= instance.OnLeftUpDiagonal;
            @LeftUpDiagonal.performed -= instance.OnLeftUpDiagonal;
            @LeftUpDiagonal.canceled -= instance.OnLeftUpDiagonal;
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @DashRight.started -= instance.OnDashRight;
            @DashRight.performed -= instance.OnDashRight;
            @DashRight.canceled -= instance.OnDashRight;
            @DashLeft.started -= instance.OnDashLeft;
            @DashLeft.performed -= instance.OnDashLeft;
            @DashLeft.canceled -= instance.OnDashLeft;
            @LP.started -= instance.OnLP;
            @LP.performed -= instance.OnLP;
            @LP.canceled -= instance.OnLP;
            @MP.started -= instance.OnMP;
            @MP.performed -= instance.OnMP;
            @MP.canceled -= instance.OnMP;
            @HP.started -= instance.OnHP;
            @HP.performed -= instance.OnHP;
            @HP.canceled -= instance.OnHP;
            @LK.started -= instance.OnLK;
            @LK.performed -= instance.OnLK;
            @LK.canceled -= instance.OnLK;
            @MK.started -= instance.OnMK;
            @MK.performed -= instance.OnMK;
            @MK.canceled -= instance.OnMK;
            @HK.started -= instance.OnHK;
            @HK.performed -= instance.OnHK;
            @HK.canceled -= instance.OnHK;
        }

        public void RemoveCallbacks(IPlayer1Actions instance)
        {
            if (m_Wrapper.m_Player1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer1Actions instance)
        {
            foreach (var item in m_Wrapper.m_Player1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player1Actions @Player1 => new Player1Actions(this);
    public interface IPlayer1Actions
    {
        void OnRightUpDiagonal(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnRightDownDiagonal(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnLeftDownDiagonal(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnLeftUpDiagonal(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnDashRight(InputAction.CallbackContext context);
        void OnDashLeft(InputAction.CallbackContext context);
        void OnLP(InputAction.CallbackContext context);
        void OnMP(InputAction.CallbackContext context);
        void OnHP(InputAction.CallbackContext context);
        void OnLK(InputAction.CallbackContext context);
        void OnMK(InputAction.CallbackContext context);
        void OnHK(InputAction.CallbackContext context);
    }
}
